### PR TITLE
fix: partial fix for the image top

### LINKED ISSUE #12: Correctly resize prediction boxes in DetectedImage

### PR DESCRIPTION
**Pull request by barelyhuman**
For: https://github.com/cryptoboid/mytag/issues/12

adds the needed calculation to get the image top when contained inside a container, the box height and box width still need to be worked on in where there's more than one tag.

Though the top works so that fixes most images where the box is somewhere in the air. 

Can be merged if you need the partial fix or if possible wait till I find why the boxes left isn't correct

### CODE REVIEW

**Comment by cryptoboid** [comment]
Amazing, I was really struggling with this one, thanks a lot! I'll wait before merging then

**Comment by barelyhuman** [comment]
@cryptoboid 
I've added error handling offsets that are adding correction where required, this is on a demo device so the sample size is small,

**Some Observations**
 - the weirder boxes are when the prediction score is less than 75% so we might wanna discard any prediction lower than 75 from getting added in the first place. 
 

Obviously this can be improved grately based on more sample images with multiple tags, Here's what we are at right now. You might wanna test it on your device as well before making a merge

IMG_97F3F34DDD3B-1

**Comment by cryptoboid** [comment]
Great, I'll be testing this later with some pictures. By the way, is the '< Keyboard' text in the header red for some reason? Is it a bug or just a test you were doing?

**Comment by barelyhuman** [comment]
No those the navigation accent that's been there all along , it isn't supposed to be?

**Comment by cryptoboid** [comment]
Huh, that's weird. It looks like this on Android:
4e75965d-9b1b-4b61-9871-c1b7f46f795f
d9fb2229-e655-4914-b111-d8549f01c9d5

When merging the dark theme PR the header text changed to white, but I forced an always-black tint here: 5c66b560429f07acf9dd953e27c219960a27d08f

In my opinion it looks better with the black tint, I didn't know it was like this in iOS. By the way, this is in the main branch, I haven't tested it on your PR

**Comment by barelyhuman** [comment]
I'll force it to be black in the next PR or add it to this PR if I find time today

**Comment by barelyhuman** [comment]
@cryptoboid , 
merged main into this branch as an update, the color is now fixed, it was using the default ios color schemes for the back till then  adding that as well in this

**Comment by cryptoboid** [comment]
Well, kinda late, but merged! I'll be working on the project again, thanks for the fix!

**Comment by barelyhuman** [comment]
I’ll pick up things as well. Kinda packed with my work and projects but I’ll let you know accordingly

**Pull request merged**
