### PR TITLE
fix(home): safearea, picker

### PR DESCRIPTION
**Pull request by barelyhuman**
wraps LoadingClassificationBar to be inside a safeareaview to avoid overlaps on gesture based nav devices (iOS, Android 9+)
also changed the picker to use a modal to avoid content overlap on iOS, making the picker unusable.

### CODE REVIEW

**Comment by barelyhuman** [comment]
https://github.com/cryptoboid/mytag/issues/24

**Comment by barelyhuman** [comment]
Do not merge yet, still have to test the resolutions. Resolved on the web ui, give me a sec

**Comment by barelyhuman** [comment]
Mergable 👍🏼 
@cryptoboid

**Comment by cryptoboid** [comment]
I've trying this out. I think that in the meantime I'll merge the safeareaview fix, but will leave the new Picker aside. The problem is that in the future I would completely ditch the picker in favor of something more like Google Photos:
image

Here all tags are shown (at least the most important ones), and the user selects one to explore. In that sense, I wouldn't add new UI features to this screen prototype. I think it's better to directly switch to the new UI.

You mentioned the new picker was to avoid content overlap on iOS, how exactly? Does it overlap with the gesture bar?

Thanks for the picker suggestion though! I'm sure it will be useful for something else (selecting albums to exclude? or maybe search filters)

**Comment by cryptoboid** [comment]
Hmmm, I see. I still haven't thought about publishing in app stores. I guess that if we are aiming for something useful besides a prototype we should publish it somewhere, at least F-Droid. I'll try to add a new UI asap so we can resolve this.

**Pull request closed without merging**
