### PR TITLE
feat(app): share image to other apps

### PR DESCRIPTION
**Pull request by barelyhuman**
https://github.com/cryptoboid/mytag/issues/18

**Note**: The sharing was tested on iOS since my android device is unable to install expo-go from the playstore or fdroid. 

If you'd like to change something just ping back on this.

### CODE REVIEW

**Comment by cryptoboid** [comment]
Great! I will be looking at this and the other PR tomorrow or Tuesday (cause of IRL stuff). 

How much do you know about architecture design in React? Because I want to revamp the object model and I don't know what works best with React, the issue is https://github.com/cryptoboid/mytag/issues/20

**Comment by barelyhuman** [comment]
> Great! I will be looking at this and the other PR tomorrow or Tuesday (cause of IRL stuff). 

Yeah that's okay. 

> How much do you know about architecture design in React? Because I want to revamp the object model and I don't know what works best with React, the issue is https://github.com/cryptoboid/mytag/issues/20

I've been using react enough, I should be able to come up with a solution, I'll go through it after IRL work in a day or so

**Comment by cryptoboid** [comment]
Quick question, what's the logic behind copying the shared file to the local filesystem in ShareButton? Instead of directly sharing it.

**Comment by barelyhuman** [comment]
While it would work on certain android systems it won’t work due to restrictions on iOS and certain android as well.   
  

  
Hence, the extra step for supporting as many platforms as possible
  
  
  
    
  

  
  
>

**Pull request merged**
